In [1]:
### Import numpy, pandas, and get more info on the data set
## Look what the unique values are for purchase, storeID, and store. In addition, I encoded CH to be 1 and MM to be 0

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"
df = pd.read_csv (r'C:\Users\rames\OneDrive\Escritorio\MMA\MMA 869 Machine Learning & Artificial Intelligence\Individual Assignment\OJ.csv')
df.info()
df.head()
df['Purchase'].unique()
df['StoreID'].unique()
df['STORE'].unique()
df['Purchase']=df['Purchase'].map({'CH':1,'MM':0})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1070 non-null   int64
 1   Purchase        1070 non-null   object
 2   WeekofPurchase  1070 non-null   int64
 3   StoreID         1070 non-null   int64
 4   PriceCH         1070 non-null   float64
 5   PriceMM         1070 non-null   float64
 6   DiscCH          1070 non-null   float64
 7   DiscMM          1070 non-null   float64
 8   SpecialCH       1070 non-null   int64
 9   SpecialMM       1070 non-null   int64
 10  LoyalCH         1070 non-null   float64
 11  SalePriceMM     1070 non-null   float64
 12  SalePriceCH     1070 non-null   float64
 13  PriceDiff       1070 non-null   float64
 14  Store7          1070 non-null   object
 15  PctDiscMM       1070 non-null   float64
 16  PctDiscCH       1070 non-null   float64
 17  ListPriceDiff   1070 non-null   float64
 18  STORE           1070 non-null   int64
dtypes: float64(11), int64(6), object(2)
memory usage: 159.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1070 non-null   int64
 1   Purchase        1070 non-null   int64
 2   WeekofPurchase  1070 non-null   int64
 3   StoreID         1070 non-null   int64
 4   PriceCH         1070 non-null   float64
 5   PriceMM         1070 non-null   float64
 6   DiscCH          1070 non-null   float64
 7   DiscMM          1070 non-null   float64
 8   SpecialCH       1070 non-null   int64
 9   SpecialMM       1070 non-null   int64
 10  LoyalCH         1070 non-null   float64
 11  SalePriceMM     1070 non-null   float64
 12  SalePriceCH     1070 non-null   float64
 13  PriceDiff       1070 non-null   float64
 14  Store7          1070 non-null   object
 15  PctDiscMM       1070 non-null   float64
 16  PctDiscCH       1070 non-null   float64
 17  ListPriceDiff   1070 non-null   float64
 18  STORE           1070 non-null   int64
dtypes: float64(11), int64(7), object(1)
memory usage: 159.0+ KB

In [2]:
pd.DataFrame(df).isna().sum() ### Check to see if there are any missing values
### I created dummies for the following features and dropped the following features accordingly 
### I dropped purchase so that my target feature did not get affected by any of my future steps taken
dummies_StoreID=pd.get_dummies(df.StoreID)
dummies_STORE=pd.get_dummies(df.STORE)
dummies_Store7=pd.get_dummies(df.Store7)
merged=pd.concat([df, dummies_StoreID, dummies_STORE], axis='columns')
merged
merged.describe().transpose()
final=merged.drop(columns=['StoreID','STORE','Purchase','Store7'])

Unnamed: 0        0
Purchase          0
WeekofPurchase    0
StoreID           0
PriceCH           0
PriceMM           0
DiscCH            0
DiscMM            0
SpecialCH         0
SpecialMM         0
LoyalCH           0
SalePriceMM       0
SalePriceCH       0
PriceDiff         0
Store7            0
PctDiscMM         0
PctDiscCH         0
ListPriceDiff     0
STORE             0
dtype: int64

,Unnamed: 0,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,...,1,2,3,4,7,0,1,2,3,4
0,1,1,237,1,1.75,1.99,0.00,0.00,0,0,...,1,0,0,0,0,0,1,0,0,0
1,2,1,239,1,1.75,1.99,0.00,0.30,0,1,...,1,0,0,0,0,0,1,0,0,0
2,3,1,245,1,1.86,2.09,0.17,0.00,0,0,...,1,0,0,0,0,0,1,0,0,0
3,4,0,227,1,1.69,1.69,0.00,0.00,0,0,...,1,0,0,0,0,0,1,0,0,0
4,5,1,228,7,1.69,1.69,0.00,0.00,0,0,...,0,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,1066,1,252,7,1.86,2.09,0.10,0.00,0,0,...,0,0,0,0,1,1,0,0,0,0
1066,1067,1,256,7,1.86,2.18,0.00,0.00,0,0,...,0,0,0,0,1,1,0,0,0,0
1067,1068,0,257,7,1.86,2.18,0.00,0.00,0,0,...,0,0,0,0,1,1,0,0,0,0
1068,1069,1,261,7,1.86,2.13,0.00,0.24,0,0,...,0,0,0,0,1,1,0,0,0,0
1069,1070,1,270,1,1.86,2.18,0.00,0.00,0,0,...,1,0,0,0,0,0,1,0,0,0

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1070.0,535.500000,309.026698,1.000000,268.250000,535.50,802.750000,1070.000000
Purchase,1070.0,0.610280,0.487915,0.000000,0.000000,1.00,1.000000,1.000000
WeekofPurchase,1070.0,254.381308,15.558286,227.000000,240.000000,257.00,268.000000,278.000000
StoreID,1070.0,3.959813,2.308984,1.000000,2.000000,3.00,7.000000,7.000000
PriceCH,1070.0,1.867421,0.101970,1.690000,1.790000,1.86,1.990000,2.090000
PriceMM,1070.0,2.085411,0.134386,1.690000,1.990000,2.09,2.180000,2.290000
DiscCH,1070.0,0.051860,0.117474,0.000000,0.000000,0.00,0.000000,0.500000
DiscMM,1070.0,0.123364,0.213834,0.000000,0.000000,0.00,0.230000,0.800000
SpecialCH,1070.0,0.147664,0.354932,0.000000,0.000000,0.00,0.000000,1.000000
SpecialMM,1070.0,0.161682,0.368331,0.000000,0.000000,0.00,0.000000,1.000000
LoyalCH,1070.0,0.565782,0.307843,0.000011,0.325257,0.60,0.850873,0.999947
SalePriceMM,1070.0,1.962047,0.252697,1.190000,1.690000,2.09,2.130000,2.290000
SalePriceCH,1070.0,1.815561,0.143384,1.390000,1.750000,1.86,1.890000,2.090000
PriceDiff,1070.0,0.146486,0.271563,-0.670000,0.000000,0.23,0.320000,0.640000
PctDiscMM,1070.0,0.059298,0.101760,0.000000,0.000000,0.00,0.112676,0.402010
PctDiscCH,1070.0,0.027314,0.062232,0.000000,0.000000,0.00,0.000000,0.252688
ListPriceDiff,1070.0,0.217991,0.107535,0.000000,0.140000,0.24,0.300000,0.440000
STORE,1070.0,1.630841,1.430387,0.000000,0.000000,2.00,3.000000,4.000000
1,1070.0,0.146729,0.354001,0.000000,0.000000,0.00,0.000000,1.000000
2,1070.0,0.207477,0.405689,0.000000,0.000000,0.00,0.000000,1.000000
3,1070.0,0.183178,0.386993,0.000000,0.000000,0.00,0.000000,1.000000
4,1070.0,0.129907,0.336358,0.000000,0.000000,0.00,0.000000,1.000000
7,1070.0,0.332710,0.471404,0.000000,0.000000,0.00,1.000000,1.000000
0,1070.0,0.332710,0.471404,0.000000,0.000000,0.00,1.000000,1.000000
1,1070.0,0.146729,0.354001,0.000000,0.000000,0.00,0.000000,1.000000
2,1070.0,0.207477,0.405689,0.000000,0.000000,0.00,0.000000,1.000000
3,1070.0,0.183178,0.386993,0.000000,0.000000,0.00,0.000000,1.000000
4,1070.0,0.129907,0.336358,0.000000,0.000000,0.00,0.000000,1.000000

In [3]:
### The following lines of code lists the features that were created
n_features = final.shape[1]
num_col_names = list(final.select_dtypes(include=np.number).columns)
print('num_col_names: {}'.format(num_col_names))

num_col_names: ['Unnamed: 0', 'WeekofPurchase', 'PriceCH', 'PriceMM', 'DiscCH', 'DiscMM', 'SpecialCH', 'SpecialMM', 'LoyalCH', 'SalePriceMM', 'SalePriceCH', 'PriceDiff', 'PctDiscMM', 'PctDiscCH', 'ListPriceDiff', 1, 2, 3, 4, 7, 0, 1, 2, 3, 4]

In [4]:
### I then proceeded to scale my data 

from sklearn.preprocessing import StandardScaler
final_num = final[num_col_names].to_numpy()
scaler = StandardScaler()
final_num = scaler.fit_transform(final_num)
X=final_num

In [5]:
## my target feature is brought back into the code
## Please noticed that as I encoded this in my first input of this file, a 1 represents someone 
## who bought CH orange juice whereas a 0 is someone who bought a MM orange juice 
y=df['Purchase']
y.shape
y.head()
X=final

(1070,)

0    1
1    1
2    1
3    0
4    1
Name: Purchase, dtype: int64

In [21]:
### I imported everything I needed to be able to split the data set into train and test
### I set a random state and did a 80%/20% split for training and testing, respectively
## I imported decision tree classifier and logistic regression
## Please note that my last method will be SVM and it is imported later in this code

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=29)
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc, roc_auc_score, classification_report, confusion_matrix, make_scorer


############ Method 1: Decision Trees
dt= DecisionTreeClassifier(random_state=29, criterion="entropy", min_samples_split=15, max_depth=10)
dt
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test,y_pred))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=10, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=15,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=29, splitter='best')

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=10, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=15,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=29, splitter='best')

[[ 65  13]
 [ 24 112]]
0.8284313725490196

In [22]:
from sklearn.model_selection import GridSearchCV
base_dt= DecisionTreeClassifier(splitter="best", class_weight=None, random_state=29)
parameters_grid={'criterion':('gini','entropy'),
                'max_depth':[2,20,100,250,300],
                'max_leaf_nodes':[None,4,8,12,16,50],
                'min_impurity_decrease': [0,0.1,0.2],
                'min_samples_leaf':[1,10,30],
               'min_samples_split':[2,10] }
dt_gs=GridSearchCV(base_dt, param_grid=parameters_grid, scoring="roc_auc", n_jobs=2, cv=5, return_train_score=True)
%time dt_gs.fit(X_train,y_train)

Wall time: 16.4 s

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=29,
                                              splitter='best'),
             iid='deprecated', n_jobs=2,
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': [2, 20, 100, 250, 300],
                         'max_leaf_nodes': [None, 4, 8, 12, 16, 50],
                         'min_impurity_decrease': [0, 0.1, 0.2],
                         'min_samples_leaf': [1, 10, 30],
                         'min_samples_split': [2, 10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='roc_auc', verbose=0)

In [24]:
## We obtained the ROC AUC score using our best hyper parameters for our decision tree model
dt_gs.best_params_
y_pred_gs=dt_gs.predict(X_test)
print(confusion_matrix(y_test, y_pred_gs))
print(roc_auc_score(y_test,y_pred_gs))

{'criterion': 'gini',
 'max_depth': 20,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0,
 'min_samples_leaf': 30,
 'min_samples_split': 2}

[[ 64  14]
 [ 21 115]]
0.833050527903469

In [26]:
### The following lines will print the results of our grid search
def cv_results_to_df(cv_results):
    results=pd.DataFrame(list(cv_results['params']))
    results['mean_fit_time']=cv_results['mean_fit_time']
    results['mean_score_time']=cv_results['mean_score_time']
    results['mean_train_score']=cv_results['mean_train_score']
    results['std_train_score']=cv_results['std_train_score']
    results['mean_test_score']=cv_results['mean_test_score']
    results['std_test_score']=cv_results['std_test_score']
    results['rank_test_score']=cv_results['rank_test_score']
    results=results.sort_values(['mean_test_score'], ascending=False)
    return results
results_gs=cv_results_to_df(dt_gs.cv_results_)
results_gs

,criterion,max_depth,max_leaf_nodes,min_impurity_decrease,min_samples_leaf,min_samples_split,mean_fit_time,mean_score_time,mean_train_score,std_train_score,mean_test_score,std_test_score,rank_test_score
220,gini,100,NaN,0.0,30,2,0.003196,0.001392,0.915561,0.003564,0.880249,0.021533,1
329,gini,250,NaN,0.0,30,10,0.003191,0.001591,0.915561,0.003564,0.880249,0.021533,1
221,gini,100,NaN,0.0,30,10,0.003186,0.001597,0.915561,0.003564,0.880249,0.021533,1
437,gini,300,NaN,0.0,30,10,0.003192,0.001396,0.915561,0.003564,0.880249,0.021533,1
436,gini,300,NaN,0.0,30,2,0.003190,0.001596,0.915561,0.003564,0.880249,0.021533,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,gini,300,16.0,0.2,30,10,0.002195,0.001397,0.500000,0.000000,0.500000,0.000000,901
520,gini,300,16.0,0.2,30,2,0.002599,0.001796,0.500000,0.000000,0.500000,0.000000,901
519,gini,300,16.0,0.2,10,10,0.002593,0.000998,0.500000,0.000000,0.500000,0.000000,901
518,gini,300,16.0,0.2,10,2,0.001994,0.001397,0.500000,0.000000,0.500000,0.000000,901
231,gini,100,NaN,0.2,10,10,0.002792,0.001197,0.500000,0.000000,0.500000,0.000000,901

In [27]:
#################### Method 2 Logistic Regression
LR=LogisticRegression()
LR.fit(X_train, y_train)
y_pred=LR.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test,y_pred))

C:\Users\rames\Python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

[[ 64  14]
 [ 14 122]]
0.8587858220211161

In [28]:
from sklearn.model_selection import GridSearchCV
LR= LogisticRegression(class_weight=None, random_state=29)
parameters_grid={'max_iter':[10,15,50,100],
                'n_jobs':[None,4,8,12,16,50],
                'warm_start':[False,True]}
LR_gs=GridSearchCV(LR, param_grid=parameters_grid, scoring="roc_auc", n_jobs=2, cv=5, return_train_score=True)
%time LR_gs.fit(X_train,y_train)

Wall time: 11.7 s

C:\Users\rames\Python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=29, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=2,
             param_grid={'max_iter': [10, 15, 50, 100],
                         'n_jobs': [None, 4, 8, 12, 16, 50],
                         'warm_start': [False, True]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='roc_auc', verbose=0)

In [29]:
## After running grid search, we obtain the best hyper parameters for our Logistic Regression and 
# the AUC value we obtained using these parameters
LR_gs.best_params_
y_pred_LR=LR_gs.predict(X_test)
print(confusion_matrix(y_test, y_pred_LR))
print(roc_auc_score(y_test,y_pred_LR))

{'max_iter': 100, 'n_jobs': None, 'warm_start': False}

[[ 64  14]
 [ 14 122]]
0.8587858220211161

In [30]:
## The following lines print the results from our grid search for our logistic regression
def cv_results_to_df(cv_results):
    results=pd.DataFrame(list(cv_results['params']))
    results['mean_fit_time']=cv_results['mean_fit_time']
    results['mean_score_time']=cv_results['mean_score_time']
    results['mean_train_score']=cv_results['mean_train_score']
    results['std_train_score']=cv_results['std_train_score']
    results['mean_test_score']=cv_results['mean_test_score']
    results['std_test_score']=cv_results['std_test_score']
    results['rank_test_score']=cv_results['rank_test_score']
    results=results.sort_values(['mean_test_score'], ascending=False)
    return results
results_LR=cv_results_to_df(LR_gs.cv_results_)
results_LR

,max_iter,n_jobs,warm_start,mean_fit_time,mean_score_time,mean_train_score,std_train_score,mean_test_score,std_test_score,rank_test_score
47,100,50.0,True,0.112499,0.001995,0.899410,0.005292,0.892900,0.022372,1
41,100,8.0,True,0.105318,0.001995,0.899410,0.005292,0.892900,0.022372,1
36,100,NaN,False,0.034308,0.001994,0.899410,0.005292,0.892900,0.022372,1
38,100,4.0,False,0.104722,0.001996,0.899410,0.005292,0.892900,0.022372,1
39,100,4.0,True,0.104920,0.002194,0.899410,0.005292,0.892900,0.022372,1
40,100,8.0,False,0.105517,0.002038,0.899410,0.005292,0.892900,0.022372,1
37,100,NaN,True,0.033314,0.002394,0.899410,0.005292,0.892900,0.022372,1
42,100,12.0,False,0.105916,0.001995,0.899410,0.005292,0.892900,0.022372,1
43,100,12.0,True,0.106116,0.001996,0.899410,0.005292,0.892900,0.022372,1
44,100,16.0,False,0.106514,0.001995,0.899410,0.005292,0.892900,0.022372,1
45,100,16.0,True,0.106714,0.001995,0.899410,0.005292,0.892900,0.022372,1
46,100,50.0,False,0.111900,0.002194,0.899410,0.005292,0.892900,0.022372,1
25,50,NaN,True,0.018151,0.001995,0.892111,0.005426,0.891046,0.026636,13
35,50,50.0,True,0.111901,0.001994,0.892111,0.005426,0.891046,0.026636,13
34,50,50.0,False,0.111900,0.001995,0.892111,0.005426,0.891046,0.026636,13
33,50,16.0,True,0.106318,0.001995,0.892111,0.005426,0.891046,0.026636,13
32,50,16.0,False,0.106318,0.001995,0.892111,0.005426,0.891046,0.026636,13
31,50,12.0,True,0.105717,0.001995,0.892111,0.005426,0.891046,0.026636,13
30,50,12.0,False,0.105717,0.002195,0.892111,0.005426,0.891046,0.026636,13
29,50,8.0,True,0.105116,0.001995,0.892111,0.005426,0.891046,0.026636,13
28,50,8.0,False,0.104919,0.001995,0.892111,0.005426,0.891046,0.026636,13
27,50,4.0,True,0.104520,0.001995,0.892111,0.005426,0.891046,0.026636,13
26,50,4.0,False,0.104528,0.001993,0.892111,0.005426,0.891046,0.026636,13
24,50,NaN,False,0.018949,0.002194,0.892111,0.005426,0.891046,0.026636,13
12,15,NaN,False,0.010771,0.002194,0.720812,0.013491,0.720232,0.020969,25
17,15,8.0,True,0.106119,0.001995,0.720812,0.013491,0.720232,0.020969,25
23,15,50.0,True,0.111899,0.001995,0.720812,0.013491,0.720232,0.020969,25
13,15,NaN,True,0.018151,0.002393,0.720812,0.013491,0.720232,0.020969,25
14,15,4.0,False,0.104922,0.002194,0.720812,0.013491,0.720232,0.020969,25
15,15,4.0,True,0.104922,0.001995,0.720812,0.013491,0.720232,0.020969,25
16,15,8.0,False,0.105919,0.002195,0.720812,0.013491,0.720232,0.020969,25
18,15,12.0,False,0.107113,0.001995,0.720812,0.013491,0.720232,0.020969,25
19,15,12.0,True,0.106515,0.001995,0.720812,0.013491,0.720232,0.020969,25
20,15,16.0,False,0.106714,0.001995,0.720812,0.013491,0.720232,0.020969,25
21,15,16.0,True,0.106913,0.001995,0.720812,0.013491,0.720232,0.020969,25
22,15,50.0,False,0.110904,0.001995,0.720812,0.013491,0.720232,0.020969,25
6,10,12.0,False,0.105517,0.001995,0.618377,0.004661,0.618665,0.021727,37
2,10,4.0,False,0.104520,0.001995,0.618377,0.004661,0.618665,0.021727,37
3,10,4.0,True,0.104320,0.001995,0.618377,0.004661,0.618665,0.021727,37
4,10,8.0,False,0.105318,0.001995,0.618377,0.004661,0.618665,0.021727,37
5,10,8.0,True,0.104925,0.001995,0.618377,0.004661,0.618665,0.021727,37
1,10,NaN,True,0.005784,0.001795,0.618377,0.004661,0.618665,0.021727,37
7,10,12.0,True,0.105320,0.001995,0.618377,0.004661,0.618665,0.021727,37
8,10,16.0,False,0.106317,0.001995,0.618377,0.004661,0.618665,0.021727,37
9,10,16.0,True,0.106515,0.001995,0.618377,0.004661,0.618665,0.021727,37
10,10,50.0,False,0.111501,0.002195,0.618377,0.004661,0.618665,0.021727,37
11,10,50.0,True,0.118283,0.002194,0.618377,0.004661,0.618665,0.021727,37
0,10,NaN,False,0.007482,0.001794,0.618377,0.004661,0.618665,0.021727,37

In [31]:
####################### Method 3 SVM
#SVM
from sklearn import svm
svm_model=svm.SVC(kernel='linear')
svm_model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [32]:

y_pred=svm_model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test,y_pred))

[[ 65  13]
 [ 17 119]]
0.8541666666666666

In [33]:
from sklearn.model_selection import GridSearchCV
svm_model= svm.SVC(class_weight=None, random_state=29)
parameters_grid={'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['linear','rbf']}
 
svm_model_gs=GridSearchCV(svm_model, param_grid=parameters_grid, scoring="roc_auc", n_jobs=2, cv=5, return_train_score=True)
%time svm_model_gs.fit(X_train,y_train)

Wall time: 15min 42s

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=29, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=2,
             param_grid={'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='roc_auc', verbose=0)

In [34]:
## These lines will get us the AUC using the best hyperparameters we could find after fine tuning
svm_model_gs.best_params_
y_pred_svm=svm_model_gs.predict(X_test)
print(confusion_matrix(y_test, y_pred_svm))
print(roc_auc_score(y_test,y_pred_svm))

{'C': 1, 'gamma': 0.001, 'kernel': 'linear'}

[[ 65  13]
 [ 17 119]]
0.8541666666666666

In [35]:
## These lines will show the results from our SVM grid search
def cv_results_to_df(cv_results):
    results=pd.DataFrame(list(cv_results['params']))
    results['mean_fit_time']=cv_results['mean_fit_time']
    results['mean_score_time']=cv_results['mean_score_time']
    results['mean_train_score']=cv_results['mean_train_score']
    results['std_train_score']=cv_results['std_train_score']
    results['mean_test_score']=cv_results['mean_test_score']
    results['std_test_score']=cv_results['std_test_score']
    results['rank_test_score']=cv_results['rank_test_score']
    results=results.sort_values(['mean_test_score'], ascending=False)
    return results
results_svm=cv_results_to_df(svm_model_gs.cv_results_)
results_svm

,C,gamma,kernel,mean_fit_time,mean_score_time,mean_train_score,std_train_score,mean_test_score,std_test_score,rank_test_score
0,1,0.0010,linear,13.071990,0.002987,0.899490,0.004948,0.891757,0.022641,1
2,1,0.0001,linear,14.807854,0.003191,0.899490,0.004948,0.891757,0.022641,1
8,100,0.0010,linear,67.019114,0.003585,0.895493,0.006624,0.891229,0.020087,3
10,100,0.0001,linear,67.059714,0.002992,0.895493,0.006624,0.891229,0.020087,3
4,10,0.0010,linear,43.165961,0.002794,0.898685,0.006028,0.890972,0.022874,5
6,10,0.0001,linear,43.535283,0.003189,0.898685,0.006028,0.890972,0.022874,5
12,1000,0.0010,linear,57.197617,0.002594,0.894914,0.005882,0.890579,0.019088,7
14,1000,0.0001,linear,57.646636,0.002793,0.894914,0.005882,0.890579,0.019088,7
15,1000,0.0001,rbf,0.122620,0.005782,0.921653,0.008168,0.834455,0.032815,9
11,100,0.0001,rbf,0.035509,0.004795,0.860446,0.005651,0.812119,0.026466,10
9,100,0.0010,rbf,0.040500,0.004180,0.967361,0.003510,0.800209,0.045902,11
5,10,0.0010,rbf,0.024933,0.004393,0.912848,0.007218,0.796490,0.040535,12
13,1000,0.0010,rbf,0.137375,0.006382,0.994516,0.001618,0.795198,0.050330,13
7,10,0.0001,rbf,0.023337,0.004986,0.821985,0.009999,0.787173,0.028445,14
1,1,0.0010,rbf,0.018351,0.004191,0.861828,0.010235,0.787059,0.036005,15
3,1,0.0001,rbf,0.021750,0.005279,0.775624,0.007873,0.757923,0.031445,16